package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/fastygo/ui8kit/utils"
)

var (
	appendIfRE      = regexp.MustCompile(`appendIf\("([^"]+)",\s*u\.\w+\)`)
	appendLiteralRE = regexp.MustCompile(`append\(classes,\s*"([^"]+)"\)`)
	flexReturnRE    = regexp.MustCompile(`return\s+\[]string\{([^}]*)\}`)
	gapCaseRE       = regexp.MustCompile(`case\s+"([^"]+)":\s*return\s+"([^"]+)"`)
	stringLiteralRE = regexp.MustCompile(`"([^"]+)"`)
)

func main() {
	inputPath := flag.String("input", "utils/props.go", "path to props.go")
	templRoot := flag.String("templ-root", ".", "root directory to scan for *_templ.go files")
	outputPath := flag.String("output", "styles/ui8kit.css", "path to generated css file")
	flag.Parse()

	src, err := os.ReadFile(filepath.Clean(*inputPath))
	if err != nil {
		exitf("read input: %v", err)
	}

	content := string(src)
	classes, patterns := collectFromProps(content)

	templClasses, err := collectTemplUtilityClasses(filepath.Clean(*templRoot))
	if err != nil {
		exitf("scan templ files: %v", err)
	}
	classes = mergeSortedUnique(classes, templClasses)

	css := buildCSS(classes, patterns)

	outFile := filepath.Clean(*outputPath)
	if err := os.MkdirAll(filepath.Dir(outFile), 0o755); err != nil {
		exitf("create output dir: %v", err)
	}
	if err := os.WriteFile(outFile, []byte(css), 0o644); err != nil {
		exitf("write output: %v", err)
	}

	fmt.Printf(
		"Generated %d concrete classes (%d from templ literals) and %d patterns to %s\n",
		len(classes),
		len(templClasses),
		len(patterns),
		outFile,
	)
}

func collectFromProps(content string) ([]string, []string) {
	classSet := map[string]struct{}{}
	patternSet := map[string]struct{}{}

	// Prefix-based utility classes from appendIf("prefix-", u.Field).
	for _, match := range appendIfRE.FindAllStringSubmatch(content, -1) {
		prefix := strings.TrimSpace(match[1])
		if prefix == "" {
			continue
		}
		patternSet[prefix+"{value}"] = struct{}{}
	}

	// Fixed classes appended directly in Resolve().
	for _, match := range appendLiteralRE.FindAllStringSubmatch(content, -1) {
		if len(match) < 2 {
			continue
		}
		className := strings.TrimSpace(match[1])
		if className == "" {
			continue
		}
		classSet[className] = struct{}{}
	}

	// Concrete classes from resolveFlex return branches.
	for _, block := range flexReturnRE.FindAllStringSubmatch(content, -1) {
		if len(block) < 2 {
			continue
		}
		for _, lit := range stringLiteralRE.FindAllStringSubmatch(block[1], -1) {
			if len(lit) < 2 {
				continue
			}
			className := strings.TrimSpace(lit[1])
			if className != "" && !strings.HasSuffix(className, "-") {
				classSet[className] = struct{}{}
			}
		}
	}

	// Concrete classes from semantic gap aliases in resolveGap().
	for _, match := range gapCaseRE.FindAllStringSubmatch(content, -1) {
		if len(match) < 3 {
			continue
		}
		alias := strings.TrimSpace(match[1])
		mapped := strings.TrimSpace(match[2])
		if alias != "" && mapped != "" {
			classSet["gap-"+mapped] = struct{}{}
		}
	}

	classes := setToSortedSlice(classSet)
	patterns := setToSortedSlice(patternSet)
	return classes, patterns
}

func buildCSS(classes, patterns []string) string {
	var b strings.Builder
	b.WriteString("/* Code generated by scripts/gen-ui8kit-css.go; DO NOT EDIT. */\n")
	b.WriteString("/* Source: utils/props.go */\n\n")
	b.WriteString("/* Concrete utility classes found in props logic. */\n")
	for _, c := range classes {
		b.WriteString(".")
		b.WriteString(escapeClass(c))
		b.WriteString(" { --ui8kit-safelist: 1; }\n")
	}

	if len(patterns) > 0 {
		b.WriteString("\n/* Pattern-based utility classes (dynamic values). */\n")
		b.WriteString("/* These are templates for runtime props and cannot be fully expanded. */\n")
		for _, p := range patterns {
			b.WriteString("/* ")
			b.WriteString(p)
			b.WriteString(" */\n")
		}
	}

	return b.String()
}

func escapeClass(name string) string {
	replacer := strings.NewReplacer(
		":", `\:`,
		"/", `\/`,
		".", `\.`,
		"[", `\[`,
		"]", `\]`,
		"(", `\(`,
		")", `\)`,
		"%", `\%`,
		"@", `\@`,
		"!", `\!`,
	)
	return replacer.Replace(name)
}

func setToSortedSlice(set map[string]struct{}) []string {
	out := make([]string, 0, len(set))
	for v := range set {
		out = append(out, v)
	}
	sort.Strings(out)
	return out
}

func mergeSortedUnique(base, extra []string) []string {
	set := make(map[string]struct{}, len(base)+len(extra))
	for _, v := range base {
		if strings.TrimSpace(v) == "" {
			continue
		}
		set[v] = struct{}{}
	}
	for _, v := range extra {
		if strings.TrimSpace(v) == "" {
			continue
		}
		set[v] = struct{}{}
	}
	return setToSortedSlice(set)
}

func collectTemplUtilityClasses(root string) ([]string, error) {
	classSet := map[string]struct{}{}
	fset := token.NewFileSet()

	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() {
			if d.Name() == ".git" || d.Name() == "node_modules" || d.Name() == "tmp" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, "_templ.go") {
			return nil
		}

		file, err := parser.ParseFile(fset, path, nil, parser.SkipObjectResolution)
		if err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}

		ast.Inspect(file, func(n ast.Node) bool {
			lit, ok := n.(*ast.CompositeLit)
			if !ok || !isUtilityPropsType(lit.Type) {
				return true
			}
			props, ok := utilityPropsFromCompositeLiteral(lit)
			if !ok {
				return true
			}
			for _, token := range strings.Fields(props.Resolve()) {
				classSet[token] = struct{}{}
			}
			return true
		})

		return nil
	})
	if err != nil {
		return nil, err
	}

	return setToSortedSlice(classSet), nil
}

func isUtilityPropsType(expr ast.Expr) bool {
	switch t := expr.(type) {
	case *ast.SelectorExpr:
		return t.Sel != nil && t.Sel.Name == "UtilityProps"
	case *ast.Ident:
		return t.Name == "UtilityProps"
	default:
		return false
	}
}

func utilityPropsFromCompositeLiteral(lit *ast.CompositeLit) (utils.UtilityProps, bool) {
	var out utils.UtilityProps
	for _, elt := range lit.Elts {
		kv, ok := elt.(*ast.KeyValueExpr)
		if !ok {
			return utils.UtilityProps{}, false
		}
		key, ok := kv.Key.(*ast.Ident)
		if !ok {
			return utils.UtilityProps{}, false
		}

		switch key.Name {
		case "Hidden":
			v, ok := boolLiteral(kv.Value)
			if !ok {
				return utils.UtilityProps{}, false
			}
			out.Hidden = v
		case "Truncate":
			v, ok := boolLiteral(kv.Value)
			if !ok {
				return utils.UtilityProps{}, false
			}
			out.Truncate = v
		case "Flex":
			if !assignString(&out.Flex, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Gap":
			if !assignString(&out.Gap, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Items":
			if !assignString(&out.Items, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Justify":
			if !assignString(&out.Justify, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "P":
			if !assignString(&out.P, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Px":
			if !assignString(&out.Px, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Py":
			if !assignString(&out.Py, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Pt":
			if !assignString(&out.Pt, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Pb":
			if !assignString(&out.Pb, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Pl":
			if !assignString(&out.Pl, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Pr":
			if !assignString(&out.Pr, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "M":
			if !assignString(&out.M, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Mt":
			if !assignString(&out.Mt, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Mb":
			if !assignString(&out.Mb, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Ml":
			if !assignString(&out.Ml, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Mr":
			if !assignString(&out.Mr, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Mx":
			if !assignString(&out.Mx, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "My":
			if !assignString(&out.My, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "W":
			if !assignString(&out.W, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "H":
			if !assignString(&out.H, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "MinW":
			if !assignString(&out.MinW, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "MaxW":
			if !assignString(&out.MaxW, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Rounded":
			if !assignString(&out.Rounded, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Shadow":
			if !assignString(&out.Shadow, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Border":
			if !assignString(&out.Border, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Bg":
			if !assignString(&out.Bg, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Text":
			if !assignString(&out.Text, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Font":
			if !assignString(&out.Font, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Leading":
			if !assignString(&out.Leading, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Tracking":
			if !assignString(&out.Tracking, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Overflow":
			if !assignString(&out.Overflow, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Z":
			if !assignString(&out.Z, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Grid":
			if !assignString(&out.Grid, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Col":
			if !assignString(&out.Col, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Row":
			if !assignString(&out.Row, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Order":
			if !assignString(&out.Order, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Grow":
			if !assignString(&out.Grow, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Shrink":
			if !assignString(&out.Shrink, kv.Value) {
				return utils.UtilityProps{}, false
			}
		case "Basis":
			if !assignString(&out.Basis, kv.Value) {
				return utils.UtilityProps{}, false
			}
		}
	}
	return out, true
}

func assignString(dst *string, expr ast.Expr) bool {
	v, ok := stringLiteral(expr)
	if !ok {
		return false
	}
	*dst = v
	return true
}

func stringLiteral(expr ast.Expr) (string, bool) {
	lit, ok := expr.(*ast.BasicLit)
	if !ok || lit.Kind != token.STRING {
		return "", false
	}
	v, err := strconv.Unquote(lit.Value)
	if err != nil {
		return "", false
	}
	return v, true
}

func boolLiteral(expr ast.Expr) (bool, bool) {
	id, ok := expr.(*ast.Ident)
	if !ok {
		return false, false
	}
	switch id.Name {
	case "true":
		return true, true
	case "false":
		return false, true
	default:
		return false, false
	}
}

func exitf(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
